### ISSUE TITLE
Modal for Consent

### ISSUE THREAD

**Issue by mzemlickis** [sebgroup/design-library#23]
Hi, I have a task that requires to have consent for data usage/marketing offers.

I put together simple consent. I will try to validate this with legal. At the same time, I wanted to align it with rest of consent prompts SEB might have, but I couldn't find one.

![image](https://user-images.githubusercontent.com/4556944/51464686-cf1e7a80-1d6e-11e9-97e1-5326c533e8f3.png)

Jess gave me a link to this as something to refer to:
https://sebgroup.github.io/bootstrap/modals

Maybe you guys have designed something like this?

**Comment by hjalmers** [comment]
Well the component itself exists and is described [here](https://designlibrary.sebgroup.com/components/modals/dialogue/#usage) in design library. In my opinion this example should use the same "component" and be based on the same principles as it's just a matter of switching content within the modal/dialogue. I'm a little bit allergic to aligning the content to the center but just for the sake of it I experimented a bit with it, [see example](https://stackblitz.com/edit/seb-modal-consent?embed=1&file=src/styles.scss&view=preview).

I prefer the default style we have for modals/dialogues as it makes the experience more consistent in my opinion. However I also see a need for modals/dialogues/messages not really triggered by user interaction or connected to the actual app or flow if you know what I mean. It could for example be informing the user about cookies, signing up for a newsletter or informing about a campaign, these are typically not part of the user interaction within an app like saving settings, adding filters etc. Not sure if that makes sense? Anyhow I added another example using toast notifications instead which I think would be perfect for cookie consent and this use case quite similar to that.

We also have another example for gathering consent in cases where we need/want to enforce it more. See screenshot below from PSD where users need to give consent for third party providers. Here we're using a separate page and not a modal.

![image](https://user-images.githubusercontent.com/1632755/51480753-53e7b380-1dc4-11e9-9443-539e6c6e806f.png)(this is from the prototype and the text has been adjusted a bit but otherwise it pretty much looks the same in production today).

What are your thoughts @JessiNygrenWalhed and @mzemlickis?

**Comment by ulde01** [comment]
@conandx Do you have any examples of this?

**Comment by JessiNygrenWalhed** [comment]
This is the modal called "Dialogue", right? Could this be ok? (the first one consent.png)
I wonder though, if the question about pension offers, should come after the user pressed the consent button? What about a step 1 & 2?
![consent](https://user-images.githubusercontent.com/45595414/53324721-d55dc480-38e1-11e9-96e2-8aeb9dcf81e9.png)
![consent_1](https://user-images.githubusercontent.com/45595414/53324728-d8f14b80-38e1-11e9-9d59-170c161fb43e.png)
![consent_2](https://user-images.githubusercontent.com/45595414/53324732-dd1d6900-38e1-11e9-88ea-8552b2ba5a7a.png)

**Comment by conandx** [comment]
Right now it's more confusing from the usability stance.... what should I press If I do not agree ?

**Comment by conandx** [comment]
@mzemlickis is this problem still open for you?

We are thinking:

1. It's important to keep it it very simple to opt out. 
2. A dialog can basically only have one question.
3. Try to avoid a wizard-like approach inside the dialog

**Comment by ulde01** [comment]
@mzemlickis How did this work out? We are curious! :)
