### ISSUE TITLE
Balancing headlines

### ISSUE THREAD

**Issue by axelgarciahenriksson** [sebgroup/design-library#25]
### Summarised topic
We should use text balancing scripts for important texts! But how much and on which texts?

### Why to use 'balancing'
To increase readability an understandability of headlines and other short texts, it is important to 'wrap' or 'balance' them nicely. A long headline which is displayed in two lines, where the second line is much shorter than the first, is very bad communication. There is a big risk that the reader misses the second line and doesn't understand what we try to say. The solution is to make the two lines of text more or less the same width. But with responsive design, this is of course tricky.

See this example from seb.se: The problem is with the headline "Enkla firman — ..."
![image](https://user-images.githubusercontent.com/36197107/51480928-9f816980-1d92-11e9-9ab8-4c6bdfa29017.png)

### How to solve it
The smart people at New York Times have made a solution to the problem and have published it on GitHub. Please see https://open.nytimes.com/headline-balancing-act-6e92d3d6119

### Where to solve it
This could be used only on headlines, but in some instances, like some wizards and forms, it is important to use on labels, radio buttons etc. 

### Speed issue
This will of course decrease loading speed. But since New York Times use this - a public site with a LOT of headlines with a LOT of visitors - I suppose their solution is fast. However, using this on every line in a form or a wizard, that might be overkill.

### Questions

- Anyone who wants to test? 
- Which texts would you need to balance?

**Comment by hjalmers** [comment]
Interesting, it’s should be fairly easy to implement on the public website however for everything else we build using modern frameworks such as angular or react we would probably need to write a wrapper for it or build something similar for those frameworks since it’s not that efficient to manipulate the DOM directly like this library does and it’s considered bad practice in the world of most modern frameworks too.

Definitely worth investigating though:) A manual but easy and efficient way is to add conditional breakpoints depending on the viewport size, however this only works when the texts arent dynamic and it’s a bit cumbersome to go through all the texts manually:S

**Comment by conandx** [comment]
DesignManagementTeam: Currently we will not try to make a global function for this. It does sound like an excellent idea but perhaps it's mostly applicable for public web channels since they currently host the most content. If someone implements it we will make a component.
