### ISSUE TITLE
Updates to typography

### ISSUE THREAD

**Issue by ulde01** [sebgroup/design-library#26]
Following adjustment to typography has been made 2019-01-21:

**H2**
weight: bold

**H3**
weight: bold

**H6**
Is no longer in use. Suggestion: make it look like H5.

**New**
- Line height is specified (it was not before) for desktop, mobile and tablet
- The biggest text size, "Display", is also available for mobile and tablet
- "Preample" is specified (it was not before) for desktop, mobile and tablet

If you are unsure, please see the complete list of sizes and line-height for each size: http://designlibrary.sebank.se/visual-identity/typography/#usage (scroll down on the page)

Ask us anything (about this)!
Thank you,
Ulrika, Design management

- [x] Vanilla https://github.com/sebgroup/vanilla-pattern-library/issues/4
- [x] Bootstrap https://github.com/sebgroup/bootstrap/issues/81
- [x] AngularMaterial https://github.com/sebgroup/seb-angular-material/issues/2#event-2155585261

**Comment by pmakro** [comment]
I would suggest making H6 at a size of 14px due to having the option of being able to differentiate between a primary and secondary headline in a supporting area/box.

By using different emphasis via typography we can introduce smaller headlines that are visible/noticeable but act more as an encapsulating headline for a paragraph rather having it the same size as regular content but in bold manner.  Thus making it harder to distinguish between a headline and statement in bold in a paragraph.

See attached images for examples.

![image](https://user-images.githubusercontent.com/11242625/54111751-eed43580-43e4-11e9-9b07-122c126565cb.png)
![image](https://user-images.githubusercontent.com/11242625/54111849-2347f180-43e5-11e9-8484-4f84aed921bf.png)

**Comment by ulde01** [comment]
@pmakro Agreed! This change is now added to the relevant frameworks, see #55

/Ulrika
