### ISSUE TITLE
SEB Design for Bootstrap components

### ISSUE THREAD

**Issue by ulde01** [sebgroup/design-library#30]
There are components in SEB Bootstrap that we should also see in Design Library: Toast notification, Cards, Breadcrumbs, Pagination, Loader, Nav bar.

- [x] Create pages with component-identfiers in Design library, so that they can show up. I do this but @hjalmers let's talk/work together if needed. This step is the fastest!
- [x] Bootstrap and Design management meet-up: See what needs to be adapted, what can be added to Design managements backlog, what about naming and descriptions, etc

**Comment by ulde01** [comment]
The page for toast notifications is created but the Bootstrap code is not showing @hjalmers :
http://designlibrary.sebank.se/components/alerts/toast-notifications/
Is the component id correct? component-toast-notifications

**Comment by hjalmers** [comment]
Yeah it's currently published as `component-toast-notifications`, [this list](https://raw.githubusercontent.com/sebgroup/bootstrap/gh-pages/sdl/sdl-bootstrap-config.json) is also updated automatically whenever code is merged to the master branch of the repository, so you can always have a look there at what should be available to the design library site. A lot of things are not on the list however as I'm not really sure on how we should add them.

A lot of things related to a design/pattern or component library actually ends up being utility classes, e.g. error messages and form errors. You just add them to existing components, it could also be things like margins and padding to avoid specifying it on/in every component, the grid is also not really a component. Might be that we still can use component id for those things too but we probably need another template to describe them.

But anyways, I guess the toast notifications should show up or do you have any clue regarding why it's not showing in SDL @splashdust?

**Comment by ulde01** [comment]
Is **Widget** in Design Library (http://designlibrary.sebank.se/components/widget/) the same component as **Cards** in SEB Bootstrap (https://sebgroup.github.io/bootstrap/cards)?

**Comment by ulde01** [comment]
Maybe we need something else for utility classes then. Let's solve this when you get back. Is it next week?

**Comment by hjalmers** [comment]
> Is **Widget** in Design Library (http://designlibrary.sebank.se/components/widget/) the same component as **Cards** in SEB Bootstrap (https://sebgroup.github.io/bootstrap/cards)?

I'd say that the widget component uses a card which is basically just a container to group content together and make it stick out, either using backgrounds, borders, shadows and working with depths.

Here are some definitions for cards and how they're used in some of the bigger frameworks.
* [Material Design](https://material.io/design/components/cards.html)
* [Semantic UI](https://semantic-ui.com/views/card.html)
* [Bootstrap](https://getbootstrap.com/docs/4.2/components/card/)
* [Foundation](https://foundation.zurb.com/building-blocks/containers.html) (search for card to see examples)

Here's also an [interesting article on cards](https://uxplanet.org/using-card-based-design-to-enhance-ux-51f965ab70cb)

Our definition of a widget is basically a card meant to be used in a dashboard, but in my opinion it's a bit specific as a card can be used for so much more than a "widget" in a dashboard. I know there's a lot of buzz regarding building reusable widgets so that we can just drop them on some page but it's probably not going to be a reusable component like buttons, inputs etc. We definitely need some UX guidelines as well as a technical contract for how widgets should be built so that they can be used together in a dashboard but to me it's more a pattern than a component. 

I think the most obvious use case for widgets as they're described now would be SEB Arena as a window and a way to navigate to underlying micro sites/apps but not sure where widget would be used elsewhere other than as pure cards for offers, ads etc?

**Comment by hjalmers** [comment]
And yes I'm back at the office next week:)

**Comment by ulde01** [comment]
These components are all connected to a page now. Some of them need descriptions. @hjalmers I would like to book a go-through with the cx-coaches one day. We sync the design and work on the descriptions. We have done the same with our other frameworks. Let's talk irl.

**Comment by ulde01** [comment]
I will close this issue now because we did what we set out to do. The result is documented in other issues, therefor no need for this high-level issue. /Ulrika
