### ISSUE TITLE
Button-link.... should just be a link

### ISSUE THREAD

**Issue by ulde01** [sebgroup/design-library#68]
**Bootstrap-sync, July 2019**

Check the reasoning behind having a button-link. Do we really need it or can it be a plain ordinary text-link?

- DMT-discussion
- update buttons/vanilla/etc?

**Comment by hjalmers** [comment]
I think one thing that's a bit confusing is that we both have alternative button, secondary button and link button. The main reason for using the link button would be to make buttons behave like links (hover, active, etc. look like links with underline) while at the same time retain the click size of a button, it's useful when you want to align them nicely with regular buttons. Since we have the alternate button (secondary button in bootstrap) it might be confusing when to use what and when to use the alternate button instead of the secondary button (outline button in bootstrap).

Alternate button (aka secondary button in bootstrap) (currently used):
![image](https://user-images.githubusercontent.com/1632755/64234036-c6da1080-cef5-11e9-8e14-aca92555b7b8.png)

Another option would of course be to just use the secondary button (aka outline version in bootstrap) of the button like this:
![image](https://user-images.githubusercontent.com/1632755/64234288-49fb6680-cef6-11e9-960d-9f6302f3c329.png)

Button link (hover state):
![image](https://user-images.githubusercontent.com/1632755/64235897-998f6180-cef9-11e9-9518-ae01d4817b19.png)

I think the case above is a tie between alternate or secondary (I personally prefer using the alternate version), which leaves the question when to use button-link?

I'd say when the button acts like a link, typical use cases would be mailto links or links to other parts of the app with route navigation i.e. the url changes. or redirects to external content. Still not crystal clear though...

Just as reference to the buttons currently availabe in the bootstrap theme.
https://sebgroup.github.io/bootstrap/buttons

**Comment by ulde01** [comment]
Thanks for your feedback Robert! Great that you add examples too. I will bring this up in our discussion in Design management. I shall be back (but it might not be this week as they are all busy. Still, will be back.)

**Comment by axelgarciahenriksson** [comment]
My opinion is that the Alternative button has a good use case as a ’tertiary button’ for the ‘extra’ functionality one might have. For example, when editing user authorizations, one open a user and the main actions are “save changes” (primary) and “cancel” (secondary). Then there might be other, less used functions that still need to be used – delete, print, assign user to another manager – whatnot. Maybe bad examples, but you get the point. So buttons for actions. The consequence for this then would e that in Roberts example, one should use Secondary button (aka outline version in Bootstrap).

But when they are links – use links, as Robert say.
