### ISSUE TITLE
FontAwesome - far or fal ?

### ISSUE THREAD

**Issue by akyataapp** [sebgroup/design-library#77]
With the new decision of using regular instead of light for fontawesome I think that icons are:
 1. too visible
 2. not aligned with text
 3. thicker than the button text

I think we should consider using the light version.

In the image below the regular is on the left and light on the right:

![image](https://user-images.githubusercontent.com/10268357/65431724-3880ec80-de1a-11e9-848e-be28320614d6.png)

// Atay Akyüz

**Comment by ghost** [comment]
Hi Atay,
we hear you 😄but don´t agree. The regular icons are more aligned with the rest of the design. When the icons are used in these small sizes, they need a bit more weight. Otherwise, in some cases, they hardly are visible.

The alignment with the text you talk about, that the text and the icon not align eachother is of course something that has to be adjusted. I don´t understand why the regular icon should act any different from the light version?

Best, Jessi

**Comment by ulde01** [comment]
Atay, I hope you felt your question (feedback!) was received. I closed the issue but if you disagree with this, please let me know! /Ulrika
