### ISSUE TITLE
Focus state - 4 px gradiant, Blue and Red (update)

### ISSUE THREAD

**Issue by ulde01** [sebgroup/design-library#82]
**Change**

Focus state on interactive components (button, link, table row, logotype, etc) goes from a flat 3 px outline in "Dark Blue 2", to a gradient 4 px outline:

![image](https://user-images.githubusercontent.com/45568194/85997618-008e8180-ba0a-11ea-8678-c441931bbffa.png)

**Blue**
- Blue focus state is a gradient 4 px outline in seb-blue/#41B0EE:
- box-shadow: 0 0 4px 1px #41B0EE;

**Red**
- Red focus state is a gradient 4 px outline in seb-red/#F03529:
- box-shadow: 0 0 4px 1px $seb-red;

**Reason**
This time we focused on the focus state for blue and red buttons but the goal is to bring a consistency throughout our components and frameworks, so these colours could be applied on all interactive components.

In Design Library, we usually design for normal, hover, selected, pressed and disable states. We will change the name "selected" to "focus" to match the css term. It describes what it is - where the focus lands when I use my keyboard to tab in the ui. 

**Todo's**
- Update accessibility instructions in Design Library
- Change name from "selected" to "focus" (many images and texts to change, so it will happen over time)
- Update in Bootstrap https://github.com/sebgroup/bootstrap/issues/367
- One source with colours names

**Comment by ulde01** [comment]
Leopold will build a few examples and show us. But our thinking is a shadow of 1px in Dark Blue 2.

**Comment by ulde01** [comment]
6px 
![image](https://user-images.githubusercontent.com/45568194/77173679-2f6a9280-6ac0-11ea-93b0-880982bb7f75.png)

**Comment by hjalmers** [comment]
Hi, started looking at this and realised that perhaps we haven't decided on anything yet? Anyways when I added the "new" focus style to the buttons it looks like this:

![image](https://user-images.githubusercontent.com/1632755/82803927-a7b75080-9e81-11ea-8394-2f726aa4b98f.png)

Note that the state above is with focus and hover state (hover state is lighter than the default state). Personally I think the focus color should reflect the state of the element that has focus so it shouldn't always be blue. Current is how it's right now, new blue uses what is specified in this issue, I think it would work if the was perhaps `box-shadow: 0 0 4px 1px $color` instead of `box-shadow: 0 0 3px 0 $color` and if the it has some opacity as well otherwise the buttons are going to look smeared/blurred.

**Comment by ulde01** [comment]
**Design decision 2020-06-15**

**Change**
Focus state on interactive components goes from a flat 3 px outline in "Dark Blue 2", to a gradient 4 px outline in "Blue":
- box-shadow: 0 0 4px 1px rgba(#41B0EE, 1); (seb-blue)

**Reason**
To bring consistency throughout our frameworks.

Exceptions (Delete-button, Sell-button, Tabs, etc) will be described on each component page.
